title:            eccentric engineering
url:              http://eccentricengineering.github.io/
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics:
timezone:         NYC/Sydney
paginate: 5
links:
  - name:         About
    url:          /about
  - name:         Project
    url:          /project
